#!/bin/bash
while read oldrev newrev ref
do
    if [[ $ref = refs/heads/gh-pages ]];
    then
        echo "Deploying 'gh-pages' branch to production"
        git --work-tree=$HOME/git/yv --git-dir=$HOME/git/yv.git checkout --force gh-pages
        exit 0
    fi
done
